
site_name: apartment.at API v1
pages:
  - Home: index.md
  - Authentication: authentication.md
  - Apartments: apartments.md
  - Availability: availability.md
  - Bookings: bookings.md
  - Prices: prices.md
  - Disable the API: disable.md
  - Errors: errors.md
theme: readthedocs